# Site settings
title:            WordPress Security Checklist
email:            rafaelfunchal@gmail.com
baseurl:          "" # the subpath of your site, e.g. /blog/
url:              "http://wpsecuritychecklist.org" # the base hostname & protocol for your site
twitter_username: rafaelfunchal
github_username:  rafaelfunchal
image:            "/img/screenshot.png"
markdown:         kramdown
kramdown:
   input:         GFM
exclude:          ["README.md"]
paginate:         10
paginate_files:
  - index.html
  - index.br.html
  - index.es.html
  - index.ja.html
encoding:         UTF-8
future:           false

# Permalinks
permalink:   pretty

# Gems
gems:             ['jekyll-pagination', 'jekyll-language-plugin']

# Languages
language_data:         data.lang.%%
language_includes_dir: _i18n
languages:             ['en', 'br', 'ja', 'es']
