# Site settings
title:            WordPress Security Checklist
email:            rafaelfunchal@gmail.com
baseurl:          "" # the subpath of your site, e.g. /blog/
url:              "https://wpsecuritychecklist.org" # the base hostname & protocol for your site
twitter_username: rafaelfunchal
github_username:  rafaelfunchal
image:            "/img/screenshot.png"
markdown:         kramdown
kramdown:
   input:         GFM
exclude:          [ "README.md" ]
paginate:         10
paginate_file:    index.html
encoding:         UTF-8
future:           false

# Permalinks
permalink:   pretty

# Gems
gems:
  - github-pages
  - jekyll-paginate
  - jekyll-language-plugin

# Languages
language_data:         data.lang.%%
language_includes_dir: _i18n
languages:             [ 'en', 'br', 'es', 'ja' ]
